### ISSUE TITLE
Make all singularity ores and ultimate ingot ores automatable

### ISSUE THREAD

**Issue by Toastunn** [Toastuun/pain#19]
all ultimate ingot ingots should be automatable now

**Comment by weegeeday** [comment]
lapis planned + being worked on, currently close to done.

**Comment by weegeeday** [comment]
![Image](https://github.com/Toastunn/ToasTech_Support_Repository/assets/38634611/55790b26-a445-4368-b8b4-c4dac14fb1d7)

**Comment by weegeeday** [comment]
to note:
lapis automation has a few items that are produced, and not used:
iron nugget
zinc nugget
crushed salt

**Comment by Toastunn** [comment]
make osmium recipes, texture osmium tetroxide

![Image](https://github.com/Toastunn/ToasTech_Support_Repository/assets/150636561/1842496d-e894-43b8-94ff-652ca0b0fca6)

**Comment by Toastunn** [comment]
osmium fully done

**Comment by Toastunn** [comment]
nickel and aluminum fully done

![Image](https://github.com/Toastunn/ToasTech_Support_Repository/assets/150636561/da227949-5fe1-48b4-b99c-791130529fa6)



![Image](https://github.com/Toastunn/ToasTech_Support_Repository/assets/150636561/f484cbdf-90dc-479d-9319-69b17943e33f)

**Comment by Toastunn** [comment]
uranium, lead, silver, tin, iridium


![Image](https://github.com/Toastunn/ToasTech_Support_Repository/assets/150636561/6d7f5e33-824c-44c7-9dcc-e1bc3d9c5018)



![Image](https://github.com/Toastunn/ToasTech_Support_Repository/assets/150636561/572f03c0-c457-412e-8f1d-c027d6a63300)



![Image](https://github.com/Toastunn/ToasTech_Support_Repository/assets/150636561/acf58497-9a13-412a-898e-7c8702ebbe66)



![Image](https://github.com/Toastunn/ToasTech_Support_Repository/assets/150636561/6a65152f-147f-44b5-8bf1-2cf8d55ead70)



![Image](https://github.com/Toastunn/ToasTech_Support_Repository/assets/150636561/5cbc7848-3b37-45c6-8335-1c95f285e993)

**Comment by Toastunn** [comment]
texture lead oxide and uraninite
(this is now done)

**Comment by weegeeday** [comment]
done!
