### ISSUE TITLE
Make recipe for liquid sunshine

### ISSUE THREAD

**Issue by Toastunn** [Toastuun/pain#20]

**Comment by weegeeday** [comment]
![Image](https://github.com/Toastunn/ToasTech_Support_Repository/assets/38634611/24729f3b-92e5-4227-9341-fde6ce475713)

**Comment by weegeeday** [comment]
![Image](https://github.com/Toastunn/ToasTech_Support_Repository/assets/38634611/9a427773-82c7-4997-b5e7-03e42ddacea2)

**Comment by weegeeday** [comment]
[https://github.com/Toastunn/ToasTech_Support_Repository/commit/f8c7b2e0dddd8e79780d7fa0ff2ec090b615bd0b](url)

this commit gets most of the recipie, but it dosent work. no ct errors, but it doesnt appear in-game.

**Comment by weegeeday** [comment]
fixed issue. was missing output. (i am blind)
liquid sunshine can now be produced, and fire water already has a recipe.
glowstone is already automatable, and sunflowers are farmable.
